package com.garitawatch.app.domain.model

data class PortSearchIndex(
    val portName: String,
    val keywords: List<String>
)

val portSearchIndex = listOf(
    PortSearchIndex("Alexandria Bay", listOf("alexandria bay", "lansdowne")),
    PortSearchIndex("Blaine", listOf("blaine", "surrey")),
    PortSearchIndex("Buffalo/Niagara Falls", listOf("buffalo/niagara falls", "fort erie")),
    PortSearchIndex("Calais", listOf("calais", "st. stephen")),
    PortSearchIndex("Champlain", listOf("champlain", "saint-bernard-de-lacolle")),
    PortSearchIndex("Derby Line", listOf("derby line", "stanstead")),
    PortSearchIndex("Detroit", listOf("detroit", "windsor")),
    PortSearchIndex("Highgate Springs", listOf("highgate springs", "saint-armand")),
    PortSearchIndex("Houlton", listOf("houlton", "woodstock")),
    PortSearchIndex("International Falls", listOf("international falls", "fort frances")),
    PortSearchIndex("Jackman", listOf("jackman", "saint-theophile")),
    PortSearchIndex("Lynden", listOf("lynden", "aldergrove")),
    PortSearchIndex("Madawaska", listOf("madawaska", "edmundston")),
    PortSearchIndex("Massena", listOf("massena", "cornwall")),
    PortSearchIndex("Norton", listOf("norton", "stanstead")),
    PortSearchIndex("Ogdensburg", listOf("ogdensburg", "prescott")),
    PortSearchIndex("Pembina", listOf("pembina", "emerson")),
    PortSearchIndex("Port Huron", listOf("port huron", "sarnia")),
    PortSearchIndex("Sault Ste. Marie", listOf("sault ste. marie", "sault ste. marie")),
    PortSearchIndex("Sumas", listOf("sumas", "abbotsford")),
    PortSearchIndex("Sweetgrass", listOf("sweetgrass", "coutts")),
    PortSearchIndex("Andrade", listOf("andrade", "los algodones")),
    PortSearchIndex("BOTA CARGO FACILITY", listOf("bota cargo facility", "ciudad juarez")),
    PortSearchIndex("Bridge of the Americas Port of Entry", listOf("bridge of the americas port of entry", "ciudad juarez")),
    PortSearchIndex("Brownsville", listOf("brownsville", "matamoros")),
    PortSearchIndex("Calexico", listOf("calexico", "mexicali")),
    PortSearchIndex("Columbus", listOf("columbus", "puerto palomas")),
    PortSearchIndex("Del Rio", listOf("del rio", "ciudad acuna")),
    PortSearchIndex("Douglas (Raul Hector Castro)", listOf("douglas", "agua prieta")),
    PortSearchIndex("Eagle Pass", listOf("eagle pass", "piedras negras")),
    PortSearchIndex("El Paso", listOf("el paso", "ciudad juarez")),
    PortSearchIndex("Fort Hancock", listOf("fort hancock", "el porvenir")),
    PortSearchIndex("Gateway", listOf("gateway", "ciudad juarez")),
    PortSearchIndex("Hidalgo/Pharr", listOf("hidalgo", "pharr", "reynosa")),
    PortSearchIndex("Laredo", listOf("laredo", "nuevo laredo")),
    PortSearchIndex("Lukeville", listOf("lukeville", "sonoyta")),
    PortSearchIndex("Marcelino Serna", listOf("marcelino serna", "guadalupe")),
    PortSearchIndex("Naco", listOf("naco", "naco")),
    PortSearchIndex("Nogales", listOf("nogales", "nogales")),
    PortSearchIndex("Otay Mesa", listOf("otay mesa", "tijuana")),
    PortSearchIndex("Otay Mesa Port of Entry", listOf("otay mesa port of entry", "tijuana")),
    PortSearchIndex("Paso Del Norte", listOf("paso del norte", "ciudad juarez")),
    PortSearchIndex("Presidio", listOf("presidio", "ojinaga")),
    PortSearchIndex("Progreso", listOf("progreso", "nuevo progreso")),
    PortSearchIndex("Rio Grande City", listOf("rio grande city", "camargo")),
    PortSearchIndex("Roma", listOf("roma", "ciudad miguel aleman")),
    PortSearchIndex("ROMA TEXAS", listOf("roma texas", "ciudad miguel aleman")),
    PortSearchIndex("San Luis", listOf("san luis", "san luis rio colorado")),
    PortSearchIndex("San Ysidro", listOf("san ysidro", "tijuana")),
    PortSearchIndex("Santa Teresa", listOf("santa teresa", "san jeronimo")),
    PortSearchIndex("Tecate", listOf("tecate", "tecate"))
)
